apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-project-5
  template:
    metadata:
      labels:
        app: udacity-project-5
    spec:
      containers:
        - name: udacity-project-5
          image: kabuto01/udacity-project-5:034594b
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: udacity-project-5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080